INSERT INTO patients (PK, LASTNAME, FIRSTNAME, PATIENTID, IDISSUER,DEPRECATED)
VALUES (1, 'Rossi','Mario', '1', 'NONE',0 );

INSERT INTO studies (STUDYINSTANCEUID, DEPRECATED, NUMBEROFSTUDYRELATEDSERIES, NUMBEROFSTUDYRELATEDINSTANCES, ISLEGALLYSTORED, ISEDITABLE, PATIENTFK, ACCESSIONNUMBER, STUDYID )
VALUES ('2', 0, 0, 0, 0, 1, '1', '3', '2' );


INSERT INTO series (STUDYFK, SERIESINSTANCEUID, DEPRECATED )
VALUES ('2', '1', '0' );
