CREATE TABLE "JBOSSPACSDB"."TO3PDI_CONF" 
   (	"PARAMKEY" VARCHAR2(24 BYTE) NOT NULL ENABLE, 
	"PARAMVALUE" VARCHAR2(4000 BYTE), 
	"ENABLED" NUMBER(3,0) DEFAULT '1' NOT NULL ENABLE, 
	 PRIMARY KEY ("PARAMKEY", "ENABLED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JBOSSPACSDB_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JBOSSPACSDB_TBL" ;