/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.units.htl.maps;

// Generated 29-gen-2009 10.25.36 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipment generated by hbm2java
 */
public class Equipment implements java.io.Serializable {

	private Long pk;
	private String equipmentType;
	private String manufacturer;
	private String institutionName;
	private String stationName;
	private String institutionalDepartmentName;
	private String manufacturersModelName;
	private String deviceSerialNumber;
	private Date dateOfLastCalibration;
	private Date timeOfLastCalibration;
	private String lastCalibratedBy;
	private String conversionType;
	private String secondaryCaptureDeviceId;
	private Set knownNodes = new HashSet(0);
	private Set series = new HashSet(0);

	public Equipment() {
	}

	public Equipment(String equipmentType, String manufacturer,
			String institutionName, String stationName,
			String institutionalDepartmentName, String manufacturersModelName,
			String deviceSerialNumber, Date dateOfLastCalibration,
			Date timeOfLastCalibration, String lastCalibratedBy,
			String conversionType, String secondaryCaptureDeviceId,
			Set knownNodes, Set series) {
		this.equipmentType = equipmentType;
		this.manufacturer = manufacturer;
		this.institutionName = institutionName;
		this.stationName = stationName;
		this.institutionalDepartmentName = institutionalDepartmentName;
		this.manufacturersModelName = manufacturersModelName;
		this.deviceSerialNumber = deviceSerialNumber;
		this.dateOfLastCalibration = dateOfLastCalibration;
		this.timeOfLastCalibration = timeOfLastCalibration;
		this.lastCalibratedBy = lastCalibratedBy;
		this.conversionType = conversionType;
		this.secondaryCaptureDeviceId = secondaryCaptureDeviceId;
		this.knownNodes = knownNodes;
		this.series = series;
	}

	public Long getPk() {
		return this.pk;
	}

	public void setPk(Long pk) {
		this.pk = pk;
	}

	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getInstitutionalDepartmentName() {
		return this.institutionalDepartmentName;
	}

	public void setInstitutionalDepartmentName(
			String institutionalDepartmentName) {
		this.institutionalDepartmentName = institutionalDepartmentName;
	}

	public String getManufacturersModelName() {
		return this.manufacturersModelName;
	}

	public void setManufacturersModelName(String manufacturersModelName) {
		this.manufacturersModelName = manufacturersModelName;
	}

	public String getDeviceSerialNumber() {
		return this.deviceSerialNumber;
	}

	public void setDeviceSerialNumber(String deviceSerialNumber) {
		this.deviceSerialNumber = deviceSerialNumber;
	}

	public Date getDateOfLastCalibration() {
		return this.dateOfLastCalibration;
	}

	public void setDateOfLastCalibration(Date dateOfLastCalibration) {
		this.dateOfLastCalibration = dateOfLastCalibration;
	}

	public Date getTimeOfLastCalibration() {
		return this.timeOfLastCalibration;
	}

	public void setTimeOfLastCalibration(Date timeOfLastCalibration) {
		this.timeOfLastCalibration = timeOfLastCalibration;
	}

	public String getLastCalibratedBy() {
		return this.lastCalibratedBy;
	}

	public void setLastCalibratedBy(String lastCalibratedBy) {
		this.lastCalibratedBy = lastCalibratedBy;
	}

	public String getConversionType() {
		return this.conversionType;
	}

	public void setConversionType(String conversionType) {
		this.conversionType = conversionType;
	}

	public String getSecondaryCaptureDeviceId() {
		return this.secondaryCaptureDeviceId;
	}

	public void setSecondaryCaptureDeviceId(String secondaryCaptureDeviceId) {
		this.secondaryCaptureDeviceId = secondaryCaptureDeviceId;
	}

	public Set getKnownNodes() {
		return this.knownNodes;
	}

	public void setKnownNodes(Set knownNodes) {
		this.knownNodes = knownNodes;
	}

	public Set getSeries() {
		return this.series;
	}

	public void setSeries(Set series) {
		this.series = series;
	}

}
