/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.units.htl.maps;

import java.util.SortedMap;
import java.util.TreeMap;

// Generated 24-Aug-2009 15:18:34 by Hibernate Tools 3.2.4.GA

/**
 * Knownnodes generated by hbm2java
 */
public class KnownNodes implements java.io.Serializable {

	private static final long serialVersionUID = 9053067667583355273L;
	
	private Long pk;
	private Equipment equipment;
	private PhysicalMedia physicalMedia;
	private String aeTitle;
	private String ip;
	private int port;
	private String cipherSuites;
	private String transferSyntaxUid;
	private Boolean isAnonimized;
	private Character mobile;
	private Boolean isEnabled;
	private Boolean isImageMaskingEnabled;
	private char forwardEndConfirmation;
	private String wadoURL;
	private String frameIncrementPointer;
	private Float frameTime;
	private Boolean removePatientId;
	
	// PACSWEB-67
	private Boolean toVerify;
	private String prefCallingAet;
	
	private SortedMap<String, String> supportedFrameIncrementPointers;
	private SortedMap<String, String> supportedTransferSyntaxes;
	
	private void init(){
		supportedFrameIncrementPointers=new TreeMap<String, String>(); 
		supportedFrameIncrementPointers.put("-","");
		supportedFrameIncrementPointers.put("Frame Time","(0018,1063)");
		
		supportedTransferSyntaxes=new TreeMap<String, String>(); 
		supportedTransferSyntaxes.put("-","");
		supportedTransferSyntaxes.put("JPEGLossless","1.2.840.10008.1.2.4.70");
	}
	
	public KnownNodes() {
		init();
	}

	public KnownNodes(Equipment equipment, PhysicalMedia physicalMedia,
			String aeTitle, String ip, int port) {
		this.equipment = equipment;
		this.physicalMedia = physicalMedia;
		this.aeTitle = aeTitle;
		this.ip = ip;
		this.port = port;
		init();
	}

	public KnownNodes(Equipment equipment, PhysicalMedia physicalMedia,
			String aeTitle, String ip, int port, String cipherSuites,
			String transferSyntaxUid, Boolean isAnonimized, Character mobile,
			Boolean isEnabled, Boolean isImageMaskingEnabled, char forwardEndConfirmation) {
		this.equipment = equipment;
		this.physicalMedia = physicalMedia;
		this.aeTitle = aeTitle;
		this.ip = ip;
		this.port = port;
		this.cipherSuites = cipherSuites;
		this.transferSyntaxUid = transferSyntaxUid;
		this.isAnonimized = isAnonimized;
		this.mobile = mobile;
		this.isEnabled = isEnabled;
		this.isImageMaskingEnabled = isImageMaskingEnabled;
		this.forwardEndConfirmation = forwardEndConfirmation;
		init();
	}

	public KnownNodes(Equipment equipment, PhysicalMedia physicalMedia,
			String aeTitle, String ip, int port, String cipherSuites,
			String transferSyntaxUid, Boolean isAnonimized, Character mobile,
			Boolean isEnabled, Boolean isImageMaskingEnabled) {
		this.equipment = equipment;
		this.physicalMedia = physicalMedia;
		this.aeTitle = aeTitle;
		this.ip = ip;
		this.port = port;
		this.cipherSuites = cipherSuites;
		this.transferSyntaxUid = transferSyntaxUid;
		this.isAnonimized = isAnonimized;
		this.mobile = mobile;
		this.isEnabled = isEnabled;
		this.isImageMaskingEnabled = isImageMaskingEnabled;
		init();
	}
	
	public KnownNodes(Equipment equipment, PhysicalMedia physicalMedia,
			String aeTitle, String ip, int port, String cipherSuites,
			String transferSyntaxUid, Boolean isAnonimized, Character mobile,
			Boolean isEnabled, Boolean isImageMaskingEnabled, String frameIncrementPointer,
			Float frameTime, char forwardEndConfirmation) {
		this.equipment = equipment;
		this.physicalMedia = physicalMedia;
		this.aeTitle = aeTitle;
		this.ip = ip;
		this.port = port;
		this.cipherSuites = cipherSuites;
		this.transferSyntaxUid = transferSyntaxUid;
		this.isAnonimized = isAnonimized;
		this.mobile = mobile;
		this.isEnabled = isEnabled;
		this.isImageMaskingEnabled = isImageMaskingEnabled;
		this.forwardEndConfirmation = forwardEndConfirmation;
		this.frameIncrementPointer = frameIncrementPointer;
		this.frameTime = frameTime;
		init();
	}
	
	public String getWadoURL() {
        return wadoURL;
    }

    public void setWadoURL(String wadoURL) {
        this.wadoURL = wadoURL;
    }

    public Long getPk() {
		return this.pk;
	}

	public void setPk(Long pk) {
		this.pk = pk;
	}

	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	public PhysicalMedia getPhysicalMedia() {
		return this.physicalMedia;
	}

	public void setPhysicalMedia(PhysicalMedia physicalMedia) {
		this.physicalMedia = physicalMedia;
	}

	public String getAeTitle() {
		return this.aeTitle;
	}

	public void setAeTitle(String aeTitle) {
		this.aeTitle = aeTitle;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getCipherSuites() {
		return this.cipherSuites;
	}

	public void setCipherSuites(String cipherSuites) {
		this.cipherSuites = cipherSuites;
	}

	public String getTransferSyntaxUid() {
		return this.transferSyntaxUid;
	}

	public void setTransferSyntaxUid(String transferSyntaxUid) {
		if("".equals(transferSyntaxUid))
			this.transferSyntaxUid = null;
		else
			this.transferSyntaxUid = transferSyntaxUid;
	}

	public Boolean getIsAnonimized() {
		return this.isAnonimized;
	}

	public void setIsAnonimized(Boolean isAnonimized) {
		this.isAnonimized = isAnonimized;
	}

	public Boolean getRemovePatientId() {
		return this.removePatientId;
	}

	public void setRemovePatientId(Boolean removePatientId) {
		this.removePatientId = removePatientId;
	}
	
	public Character getMobile() {
		return this.mobile;
	}

	public void setMobile(Character mobile) {
		this.mobile = mobile;
	}

	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public Boolean getisImageMaskingEnabled() {
		return this.isImageMaskingEnabled;
	}

	public void setisImageMaskingEnabled(Boolean isImageMaskingEnabled) {
		this.isImageMaskingEnabled = isImageMaskingEnabled;
	}

	public char getForwardEndConfirmation() {
		return this.forwardEndConfirmation;
	}

	public void setForwardEndConfirmation(char forwardEndConfirmation) {
		this.forwardEndConfirmation = forwardEndConfirmation;
	}

	//For PACSCORE-77

	public String getFrameIncrementPointer(){
		return this.frameIncrementPointer;	
	}
	
	public void setFrameIncrementPointer(String frameIncrementPointer) {
		if("".equals(frameIncrementPointer))
			this.frameIncrementPointer = null;
		else
			this.frameIncrementPointer = frameIncrementPointer;
	}

	public Float getFrameTime(){
		return this.frameTime;	
	}
	
	public void setFrameTime(Float frameTime) {
			this.frameTime= frameTime;
	}

	public SortedMap<String, String> getSupportedFrameIncrementPointers() {
		return supportedFrameIncrementPointers;
	}

	public SortedMap<String, String> getSupportedTransferSyntaxes() {
		return supportedTransferSyntaxes;
	}

	public Boolean getToVerify() {
		return toVerify;
	}

	public void setToVerify(Boolean toVerify) {
		this.toVerify = toVerify;
	}

	public String getPrefCallingAet() {
		return prefCallingAet;
	}

	public void setPrefCallingAet(String prefCallingAet) {
		this.prefCallingAet = prefCallingAet;
	}

	
}
