/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.units.htl.maps;

// Generated 24-Aug-2009 15:18:34 by Hibernate Tools 3.2.4.GA

/**
 * Nodesforwardmapping generated by hbm2java
 */
public class NodesForwardMapping implements java.io.Serializable {

	private NodesForwardMappingId id;
	private Byte sortOrder;

	public NodesForwardMapping() {
	}

	public NodesForwardMapping(NodesForwardMappingId id) {
		this.id = id;
	}

	public NodesForwardMapping(NodesForwardMappingId id, Byte sortOrder) {
		this.id = id;
		this.sortOrder = sortOrder;
	}

	public NodesForwardMappingId getId() {
		return this.id;
	}

	public void setId(NodesForwardMappingId id) {
		this.id = id;
	}

	public Byte getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Byte sortOrder) {
		this.sortOrder = sortOrder;
	}

}
