/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.csi.dmass.client.verificaService;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2022-03-31T17:24:28.778+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "VerificaService", 
                  wsdlLocation = "classpath:wsdl/VerificaService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class VerificaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "VerificaService");
    public final static QName VerificaServicePort = new QName("http://dmacc.csi.it/", "VerificaServicePort");
    static {
        URL url = VerificaService_Service.class.getClassLoader().getResource("wsdl/VerificaService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(VerificaService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/VerificaService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public VerificaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VerificaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VerificaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VerificaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VerificaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VerificaService
     */
    @WebEndpoint(name = "VerificaServicePort")
    public VerificaService getVerificaServicePort() {
        return super.getPort(VerificaServicePort, VerificaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificaService
     */
    @WebEndpoint(name = "VerificaServicePort")
    public VerificaService getVerificaServicePort(WebServiceFeature... features) {
        return super.getPort(VerificaServicePort, VerificaService.class, features);
    }

}
