/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.csi.dmass.client.utilityService;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2022-03-31T17:24:27.175+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "UtilityService", 
                  wsdlLocation = "classpath:wsdl/UtilityService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class UtilityService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "UtilityService");
    public final static QName UtilityPort = new QName("http://dmacc.csi.it/", "UtilityPort");
    static {
        URL url = UtilityService_Service.class.getClassLoader().getResource("wsdl/UtilityService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(UtilityService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/UtilityService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public UtilityService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UtilityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UtilityService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UtilityService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UtilityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UtilityService
     */
    @WebEndpoint(name = "UtilityPort")
    public UtilityService getUtilityPort() {
        return super.getPort(UtilityPort, UtilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityService
     */
    @WebEndpoint(name = "UtilityPort")
    public UtilityService getUtilityPort(WebServiceFeature... features) {
        return super.getPort(UtilityPort, UtilityService.class, features);
    }

}
