
CREATE OR REPLACE PROCEDURE getAllSeriesFromStudy(
  p_studyUid IN VARCHAR2,
  resultset OUT Types.ResultSet
)
AS
BEGIN
  OPEN RESULTSET FOR
    SELECT SE.SERIESINSTANCEUID, SE.MODALITY, SE.NUMBEROFSERIESRELATEDINSTANCES, SE.SERIESDESCRIPTION ,

          CASE WHEN EXISTS(SELECT sopInstanceUID FROM IMAGES IM WHERE IM.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT IM.SOPINSTANCEUID FROM IMAGES IM WHERE IM.SERIESFK = SE.SERIESINSTANCEUID and rownum=1)
          WHEN EXISTS(SELECT sopInstanceUID FROM ImagesNearline IM WHERE IM.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT IM.SOPINSTANCEUID FROM ImagesNearline IM WHERE IM.SERIESFK = SE.SERIESINSTANCEUID and rownum=1)
          WHEN EXISTS(SELECT sopInstanceUID FROM NONIMAGES NIM WHERE NIM.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT nIM.SOPINSTANCEUID FROM nonIMAGES nIM WHERE nIM.SERIESFK = SE.SERIESINSTANCEUID and rownum=1)
          WHEN EXISTS(SELECT sopInstanceUID FROM STRUCTREPS SR WHERE SR.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT SR.SOPINSTANCEUID FROM STRUCTREPS SR WHERE SR.SERIESFK = SE.SERIESINSTANCEUID and rownum=1)
          WHEN EXISTS (SELECT sopInstanceUID FROM OVERLAYS OV WHERE OV.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT OV.SOPINSTANCEUID FROM OVERLAYS OV WHERE OV.SERIESFK = SE.SERIESINSTANCEUID and rownum=1)
          WHEN EXISTS(SELECT sopInstanceUID FROM PRESSTATES PS WHERE PS.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT PS.SOPINSTANCEUID FROM PRESSTATES PS WHERE PS.SERIESFK = SE.SERIESINSTANCEUID AND ROWNUM=1)
          WHEN EXISTS(SELECT sopInstanceUID FROM KEYOBJECTS K WHERE K.SERIESFK = SE.SERIESINSTANCEUID) THEN
            (SELECT K.SOPINSTANCEUID FROM KEYOBJECTS K WHERE K.SERIESFK = SE.SERIESINSTANCEUID AND ROWNUM=1)  
          else
             NULL
          END AS sopInstanceUID
    FROM SERIES SE
    WHERE SE.STUDYFK = P_STUDYUID and SE.DEPRECATED = 0;
END getAllSeriesFromStudy;

------------------------------------------------------------------------------------------------------------------------
