/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.csi.dmass.client.delegaService.dmacc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2022-03-31T17:24:29.631+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://dmacc.csi.it/", name = "DelegaService")
@XmlSeeAlso({ObjectFactory.class, it.csi.dmass.client.delegaService.dma.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DelegaService {

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDeleganti")
    @WebResult(name = "getDelegantiResponse", targetNamespace = "http://dmacc.csi.it/", partName = "getDelegantiResponse")
    public GetDelegantiResponse getDeleganti(
        @WebParam(partName = "getDeleganti", name = "getDeleganti", targetNamespace = "http://dmacc.csi.it/")
        GetDelegantiRequest getDeleganti
    );

    @WebMethod(action = "http://dma.csi.it/DocumentiService/getDeleganti2")
    @WebResult(name = "getDeleganti2Response", targetNamespace = "http://dmacc.csi.it/", partName = "getDeleganti2Response")
    public GetDeleganti2Response getDeleganti2(
        @WebParam(partName = "getDeleganti2", name = "getDeleganti2", targetNamespace = "http://dmacc.csi.it/")
        GetDeleganti2Request getDeleganti2
    );
}
