/*
 * SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
 *
 * SPDX-License-Identifier: GPL-2.0
 */
package it.csi.dmass.client.delegaService.dmacc;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2022-03-31T17:24:29.639+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "DelegaService", 
                  wsdlLocation = "classpath:wsdl/DelegaService.wsdl",
                  targetNamespace = "http://dmacc.csi.it/") 
public class DelegaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dmacc.csi.it/", "DelegaService");
    public final static QName DelegaServicePort = new QName("http://dmacc.csi.it/", "DelegaServicePort");
    static {
        URL url = DelegaService_Service.class.getClassLoader().getResource("wsdl/DelegaService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DelegaService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/DelegaService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public DelegaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DelegaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DelegaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DelegaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DelegaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DelegaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DelegaService
     */
    @WebEndpoint(name = "DelegaServicePort")
    public DelegaService getDelegaServicePort() {
        return super.getPort(DelegaServicePort, DelegaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DelegaService
     */
    @WebEndpoint(name = "DelegaServicePort")
    public DelegaService getDelegaServicePort(WebServiceFeature... features) {
        return super.getPort(DelegaServicePort, DelegaService.class, features);
    }

}
